[package]
name = "dmd-play-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
image = "0.24"
imageproc = "0.23.0"
rusttype = "0.9"
chrono = "0.4"
